baseurl: /
highlighter: rouge
markdown: kramdown
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex

plugins:
    - jekyll-sitemap

defaults:
    -
      scope:
          path: ""
      values:
          sitemap: false
          image:
            path: /images/og-image.png
            width: 1024
            height: 640
            alt: "PHP: The Right Way"

# Excludes should be appended to the default
# https://github.com/jekyll/jekyll/blob/master/lib/site_template/_config.yml#L37-L55
exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - Gruntfile.js
   - node_modules/
   - package.json
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
   - CNAME
   - CONTRIBUTING.md
   - LICENSE
   - README.md
   - pages/example.md

future: true

title: "PHP: The Right Way"
tagline: Reference for PHP best practices
description: An easy-to-read, quick reference for PHP best practices, accepted coding standards, and links to authoritative PHP tutorials around the Web
logo: /images/og-image.png
