safe: true
baseurl: "http://smatejic.github.io/php-the-right-way"
url: http://localhost:4000

pygments: true
markdown: kramdown
permalink: date
maruku:
    use_tex:    false
    use_divs:   false
    png_engine: blahtex
    png_dir:    images/latex
    png_url:    /images/latex
